# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'transaction' do
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Firestore', '~> 6.3.0'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FacebookSDK'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'React'
        target.remove_from_project
      end
    end
  end

  # pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  # pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for transaction
  target 'transaction-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'transactionTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'transaction-tvOS' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!

#   # Pods for transaction-tvOS

#   target 'transaction-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
